app:
  name: "web-pm-go"
  version: "v0.0.1"
  port: "18080"
  configFile: ""
datasource:
  host: ""
  port: ""
  user: ""
  password: ""
redis:
  host: ""
  port: ""
  user: ""
  password: ""
log:
  logForbidStdout: false
  logFileDir: "logs"
  logFileNamePrefix: "web-pm-go"
  logFileMaxSizeM: 2
  logLevelGlobal: "debug"
  logLineFormat: ""
  logMod: 2
  logChannelCap: 4096
  logChnOverPolicy: 1
  logLevelCtlHost: ""
  logLevelCtlPort: ""
