quarkus:
  http:
    port: 8082
  native:
    native-image-xmx: 10000M
    container-build: true
  container-image:
    group: yjl
    name: quarkus-test
    tag: 1.1
  datasource:
    jdbc: false
    db-kind: mysql
    username: zhaochun1
    password: zhaochun@GITHUB
    reactive:
      idle-timeout: PT5M
      url: vertx-reactive:mysql://172.17.13.44:3306/db_web_pm
      max-size: 20
      mysql:
        charset: utf8
  log:
    level: INFO
    file:
      enable: true
      path: /home/test.log
      rotation:
        max-file-size: 100M
        max-backup-index: 100
    category:
      "org.hibernate.hql.internal.ast.QueryTranslatorImpl":
        level: INFO
      "cn.yjl":
        level: DEBUG
  hibernate-orm:
    dialect: org.hibernate.dialect.MySQL8Dialect
    "dialect.storage-engine": InnoDB
    packages:
      - cn.yjl.operation.entity
smallrye:
  config:
    locations:
      - ./external.yml