mybatis:
  mapper-locations: "classpath:com/zhaochuninhefei/webpmjava/db/mapper/*.xml"

server:
  port: "18081"

spring:
  application:
    name: "web-pm-java"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      auto-commit: true
      connection-test-query: "select 1"
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 10
      pool-name: "HikariCP-web-pm-java"
    url: "jdbc:mysql://172.17.13.44:3306/db_web_pm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true"
    type: "com.zaxxer.hikari.HikariDataSource"
    username: "zhaochun1"
    password: "zhaochun@GITHUB"
