server:
  port: 8080
  host: 0.0.0.0

mysql:
  source: "jdbc"
  connection:
    url: "jdbc:mysql://127.0.0.1:3306/quarkus_test"
    username: "root"
    password: "yinjiaolong"
  statements:
    ping: "DO 0"