server:
  port: 18089
  host: 0.0.0.0

mysql:
  source: "jdbc"
  connection:
#    url: "jdbc:mysql://localhost:3307/db_web_pm"
    url: "jdbc:mariadb://localhost:3307/db_web_pm"
    username: "zhaochun1"
    password: "zhaochun@GITHUB"
  statements:
    ping: "DO 0"