app:
  name: web-pm-gin
  version: 0.0.1
  port: "18080"
  config_file: ""
datasource:
  db_type: mysql
  host: localhost
  port: "3307"
  db_name: db_web_pm
  user: zhaochun1
  password: zhaochun@GITHUB
db_conn_pool:
  max_open_conns: 20
  max_idle_conns: 5
  conn_max_lifetime_min: 30
  conn_max_idle_time_min: 3
redis:
  host: localhost
  port: ""
  user: ""
  password: ""
log:
  log_forbid_stdout: false
  log_file_dir: logs
  log_file_name_prefix: web-pm-gin
  log_file_max_size_m: 2
  log_level_global: debug
  log_line_format: ""
  log_mod: 2
  log_channel_cap: 4096
  log_chn_over_policy: 1
  log_level_ctl_host: ""
  log_level_ctl_port: ""
