kind: Service
apiVersion: v1
metadata:
  name: web-pm-helidon-se
  labels:
    app: web-pm-helidon-se
spec:
  type: NodePort
  selector:
    app: web-pm-helidon-se
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-pm-helidon-se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-pm-helidon-se
  template:
    metadata:
      labels:
        app: web-pm-helidon-se
        version: v1
    spec:
      containers:
      - name: web-pm-helidon-se
        image: web-pm-helidon-se
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
