version: '3'

services:
  web-pm-gin:
    container_name: web-pm-gin
    image: 172.17.4.86:5000/web-pm-gin:0.0.1
    environment:
      DB_CONN_POOL_MAX_OPEN_CONNS: 100
      DB_CONN_POOL_MAX_IDLE_CONNS: 10
      DB_CONN_POOL_CONN_MAX_LIFETIME_MIN: 30
      DB_CONN_POOL_CONN_MAX_IDLE_TIME_MIN: 3
    restart: on-failure
    ports:
      - "18080:18080"
      - "9300:9300"
    volumes:
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-gin/logs:/src/github.com/zhaochuninhefei/web-performance-comparison/web-pm-gin/logs"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M

  web-pm-springboot:
    container_name: web-pm-springboot
    image: 172.17.4.86:5000/web-pm-springboot:mariadb.0.1
    environment:
      spring_datasource_hikari_idle_timeout: "180000"
      spring_datasource_hikari_max_lifetime: "1800000"
      spring_datasource_hikari_maximum_pool_size: "100"
      spring_datasource_hikari_minimum_idle: "10"
      spring_datasource_driver_class_name: "org.mariadb.jdbc.Driver"
      spring_datasource_url: "jdbc:mariadb://192.168.60.60:3308/db_web_pm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true"
    restart: on-failure
    ports:
      - "18081:18081"
    volumes: 
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-springboot/logs:/logs"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M

  web-pm-sbt-vt:
    container_name: web-pm-sbt-vt
    image: 172.17.4.86:5000/web-pm-sbt-vt:mariadb.0.1
    environment:
      spring_datasource_hikari_idle_timeout: "180000"
      spring_datasource_hikari_max_lifetime: "1800000"
      spring_datasource_hikari_maximum_pool_size: "100"
      spring_datasource_hikari_minimum_idle: "10"
      spring_datasource_driver_class_name: "org.mariadb.jdbc.Driver"
      spring_datasource_url: "jdbc:mariadb://192.168.60.60:3308/db_web_pm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true"
    restart: on-failure
    ports:
      - "18090:18090"
    volumes: 
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-sbt-vt/logs:/logs"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M

  web-pm-quarkus:
    container_name: web-pm-quarkus
    image: 172.17.4.86:5000/yjl/web-pm-quarkus:0.0.1
    environment:
      TZ: Asia/Shanghai
    restart: on-failure
    ports:
      - "18082:18082"
    command:
      - "./application"
      - "-Dsmallrye.config.locations=./config/external.yml"
    volumes: 
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-quarkus/logs:/work/log"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M

  web-pm-vertx-jar:
    container_name: web-pm-vertx-jar
    image: 172.17.4.86:5000/web-pm-vertx-jar:0.0.1
    restart: on-failure
    ports:
      - "18083:18083"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M

  web-pm-vertx-native:
    container_name: web-pm-vertx-native
    image: 172.17.4.86:5000/web-pm-vertx-native:0.0.1
    restart: on-failure
    ports:
      - "18084:18083"
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 2048M
        reservations:
          memory: 512M
