version: '3'

services:
  web-pm-go:
    container_name: web-pm-go
    image: 172.17.4.86:5000/web-pm-go:0.0.1
    extra_hosts:
      - "redis-brood-base:172.17.4.118"
      - "mysql-brood-base:172.17.13.13"
    restart: on-failure
    ports:
      - "18080:18080"
      - "9300:9300"
    volumes:
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-go/config:/src/github.com/zhaochuninhefei/web-performance-comparison/web-pm-go/config"
      - "/data/volumes/github.com/zhaochuninhefei/web-performance-comparison/web-pm-go/logs:/src/github.com/zhaochuninhefei/web-performance-comparison/web-pm-go/logs"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          memory: 512M

  web-pm-java:
    container_name: web-pm-java
    image: 172.17.4.86:5000/web-pm-java:0.0.1-SNAPSHOT
    extra_hosts:
      - "redis-brood-base:172.17.4.118"
      - "mysql-brood-base:172.17.13.13"
    environment:
      brood_redis_mode: "standalone"
    restart: on-failure
    ports:
      - "18081:18081"
    volumes: 
      - "/data/volumes/web-pm-java:/home/web-pm-java"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1024M
        reservations:
          memory: 512M

