app:
  name: web-pm-go
  version: 0.0.1
  port: "18080"
  configFile: ""
datasource:
  host: localhost
  port: "3307"
  user: ""
  password: ""
redis:
  host: localhost
  port: ""
  user: ""
  password: ""
log:
  logForbidStdout: false
  logFileDir: logs
  logFileNamePrefix: ""
  logFileMaxSizeM: 0
  logLevelGlobal: debug
  logLineFormat: ""
  logMod: 0
  logChannelCap: 0
  logChnOverPolicy: 0
  logLevelCtlHost: ""
  logLevelCtlPort: ""
