app:
  name: ""
  version: ""
  port: ""
  configFile: ""
datasource:
  host: ""
  port: ""
  user: ""
  password: ""
redis:
  host: ""
  port: ""
  user: ""
  password: ""
log:
  logForbidStdout: false
  logFileDir: logs
  logFileNamePrefix: ""
  logFileMaxSizeM: 0
  logLevelGlobal: debug
  logLineFormat: ""
  logMod: 0
  logChannelCap: 0
  logChnOverPolicy: 0
  logLevelCtlHost: ""
  logLevelCtlPort: ""
