app:
  name: web-pm-go
  version: 0.0.1
  port: "18080"
  configFile: ""
datasource:
  host: 172.17.13.44
  port: "3306"
  user: zhaochun1
  password: zhaochun@GITHUB
dbConnPool:
  maxOpenConns: 100
  maxIdleConns: 10
  ConnMaxLifetimeMin: 60
  ConnMaxIdleTimeMin: 10
redis:
  host: localhost
  port: ""
  user: ""
  password: ""
log:
  logForbidStdout: false
  logFileDir: logs
  logFileNamePrefix: web-pm-go
  logFileMaxSizeM: 2
  logLevelGlobal: debug
  logLineFormat: ""
  logMod: 2
  logChannelCap: 4096
  logChnOverPolicy: 1
  logLevelCtlHost: ""
  logLevelCtlPort: ""
